### ISSUE TITLE
[BUG] Cannot remove policy from read_only indices

### ISSUE THREAD

**Issue by thalurur** [opensearch-project/index-management#171] opened 2021-10-25 21:04 UTC
**Describe the bug**
Can manage indices that are read_only or has read_only_allow_delete blocks or make the index read_only as part of the policy. 
But once a read_only index is managed it cannot be unmanaged/policy cannot be removed from it because of failure to update auto_manage index settings to the index.

**Expected behavior**
Remove policies from read_only indices

**Comment by louzadod** [comment] 2021-11-02 19:37
I could reproduce this bug with OS 1.1.0

**Comment by dbbaughe** [comment] 2021-12-03 19:58
Looks like fix was released in 1.2 release, closing

**Closed by dbbaughe** 2021-12-03 19:58 UTC
Labels: bug
